name: Repository Mirroring

on:
  push:
    branches: [ main ]
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Mirror to GitLab
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: https://gitlab.com/OscarLawrence/UCP.git
        ssh_private_key: ${{ secrets.GITLAB_SSH_KEY }}
    
    - name: Mirror to Bitbucket  
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: https://bitbucket.org/OscarLawrence/ucp.git
        ssh_private_key: ${{ secrets.BITBUCKET_SSH_KEY }}
    
    - name: Mirror to Codeberg
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: https://codeberg.org/OscarLawrence/UCP.git
        ssh_private_key: ${{ secrets.CODEBERG_SSH_KEY }}

  notify:
    needs: mirror
    runs-on: ubuntu-latest
    steps:
    - name: Notify mirror completion
      run: |
        echo "UCP mirrored to:"
        echo "- GitLab: https://gitlab.com/OscarLawrence/UCP"
        echo "- Bitbucket: https://bitbucket.org/OscarLawrence/ucp" 
        echo "- Codeberg: https://codeberg.org/OscarLawrence/UCP"